import Head from "next/head";
import styles from "./home/Home.module.scss";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Screen from "./home/Screen";
import Project from "./home/Project";
import Enjoy from "./home/Enjoy";
import Fall from "./home/Fall";
import Program from "./home/Program";

export default function Home() {
  return (
    <>
      <Head>
        <title>Anjit Pariyar - Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        <Screen />
        <Enjoy />
        <Project />
        <Fall />
        <Program />
      </main>

      <Footer />
    </>
  );
}
